source 'https://rubygems.org'

gem 'dotenv'
gem 'rake'
gem 'middleman', '~> 4.2'
gem 'middleman-autoprefixer', '~> 2.7'
gem 'imgurapi'
gem 'sqlite3'
gem 'require_all'
gem 'activerecord'
gem 'pry-byebug'
